{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pickle\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import seaborn as sns\n",
    "from pathlib import Path\n",
    "from sklearn.linear_model import LinearRegression\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error\n",
    "from sklearn.linear_model import ElasticNet\n",
    "from sklearn.ensemble import RandomForestRegressor\n",
    "from sklearn import datasets\n",
    "from sklearn.tree import DecisionTreeClassifier\n",
    "from sklearn.model_selection import KFold, cross_val_score\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import StandardScaler,OneHotEncoder, LabelEncoder\n",
    "import tensorflow as tf\n",
    "\n",
    "# Function to load models\n",
    "def load_models():\n",
    "  model1 = pickle.load(open(\"model.pkl\", \"rb\"))\n",
    "  return model1\n",
    "\n",
    "# Load models\n",
    "model = load_models()\n",
    "\n",
    "# Form variables\n",
    "variables = ['track_popularity', 'danceability', 'energy', 'key', 'loudness', 'mode',\n",
    "       'speechiness', 'acousticness', 'instrumentalness', 'liveness',\n",
    "       'valence', 'tempo', 'duration_sec', 'months',\n",
    "       'playlist_genre_latin', 'playlist_genre_pop', 'playlist_genre_r&b',\n",
    "       'playlist_genre_rap', 'playlist_genre_rock',\n",
    "       'playlist_subgenre_big room', 'playlist_subgenre_classic rock',\n",
    "       'playlist_subgenre_dance pop', 'playlist_subgenre_electro house',\n",
    "       'playlist_subgenre_electropop', 'playlist_subgenre_gangster rap',\n",
    "       'playlist_subgenre_hard rock', 'playlist_subgenre_hip hop',\n",
    "       'playlist_subgenre_hip pop', 'playlist_subgenre_indie poptimism',\n",
    "       'playlist_subgenre_latin hip hop', 'playlist_subgenre_latin pop',\n",
    "       'playlist_subgenre_neo soul', 'playlist_subgenre_new jack swing',\n",
    "       'playlist_subgenre_permanent wave', 'playlist_subgenre_pop edm',\n",
    "       'playlist_subgenre_post-teen pop',\n",
    "       'playlist_subgenre_progressive electro house',\n",
    "       'playlist_subgenre_reggaeton', 'playlist_subgenre_southern hip hop',\n",
    "       'playlist_subgenre_trap', 'playlist_subgenre_tropical',\n",
    "       'playlist_subgenre_urban contemporary']\n",
    "\n",
    "def predict(model, user_input):\n",
    "  prediction = model.predict(user_input)\n",
    "  return prediction\n",
    "\n",
    "st.title(\"Regression Model Dashboard\")\n",
    "\n",
    "# Layout for dashboard and form\n",
    "col1 = st.columns(1)\n",
    "\n",
    "with col1:\n",
    "  # Display charts or text for model 1\n",
    "  st.subheader(\"Model 1\")\n",
    "  # Add charts or text based on model 1\n",
    "\n",
    "column_groups = {\n",
    "  \"Genre\": ['playlist_genre_latin', 'playlist_genre_pop', 'playlist_genre_r&b',\n",
    "       'playlist_genre_rap', 'playlist_genre_rock',],\n",
    "  \"Subgenre\": ['playlist_subgenre_big room', 'playlist_subgenre_classic rock',\n",
    "       'playlist_subgenre_dance pop', 'playlist_subgenre_electro house',\n",
    "       'playlist_subgenre_electropop', 'playlist_subgenre_gangster rap',\n",
    "       'playlist_subgenre_hard rock', 'playlist_subgenre_hip hop',\n",
    "       'playlist_subgenre_hip pop', 'playlist_subgenre_indie poptimism',\n",
    "       'playlist_subgenre_latin hip hop', 'playlist_subgenre_latin pop',\n",
    "       'playlist_subgenre_neo soul', 'playlist_subgenre_new jack swing',\n",
    "       'playlist_subgenre_permanent wave', 'playlist_subgenre_pop edm',\n",
    "       'playlist_subgenre_post-teen pop',\n",
    "       'playlist_subgenre_progressive electro house',\n",
    "       'playlist_subgenre_reggaeton', 'playlist_subgenre_southern hip hop',\n",
    "       'playlist_subgenre_trap', 'playlist_subgenre_tropical',\n",
    "       'playlist_subgenre_urban contemporary'],    \n",
    "}\n",
    "int_vars = ['track_popularity', 'danceability', 'energy', 'key', 'loudness', 'mode',\n",
    "       'speechiness', 'acousticness', 'instrumentalness', 'liveness',\n",
    "       'valence', 'tempo', 'duration_sec', 'months']\n",
    "\n",
    "# User input form\n",
    "st.subheader(\"Make a Prediction\")\n",
    "user_input = {}\n",
    "for var in variables:\n",
    "  user_input[var] = st.selectbox(var, [1, 2, 3])  # Replace with appropriate options\n",
    "\n",
    "# Sliders for integer variables\n",
    "for var in int_vars:\n",
    "  user_input[var] = st.slider(var, min_value=..., max_value=..., value=...)\n",
    "\n",
    "# Submit button and prediction display\n",
    "if st.button(\"Predict\"):\n",
    "  # Make prediction using the chosen model\n",
    "  prediction = predict(model, user_input)\n",
    "  st.write(f\"Number of predicted streams: {prediction}\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "machinelearn",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python",
   "version": "3.12.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
